#!/usr/bin/python3
import praw
import curses
import textwrap # needed for properly presenting paragraphs
from sys import argv, stdout, stderr
from datetime import datetime # for parsing timestamps
from os import getcwd # used for the help message
from warnings import filterwarnings
filterwarnings("ignore", category=ResourceWarning)
# We get a warning because the SSL connection is not closed, but according to the PRAW people this is intentional, since the garbage collector takes care of it apparently

# structure is the same as in my ncurses labyrinth game
# we're doing argument processing inside main and reply depending on what main returns
# for now no arguments, we just start up in interactive mode




def displayComments(standardScreen, screenMaxY, screenMaxX, submissionsPad, reddit, currentSubreddit, submissionToOpen, submissionsNumberLimit):
	# we open a new window with the contents of the submission
	submissions = reddit.get_subreddit(currentSubreddit).get_hot(limit=submissionsNumberLimit)
	yCoordComments = 0
	xCoordComments = 0
	
	submissionsPad.erase()
	commentsPad = curses.newpad(200*100, screenMaxX+1) #200 is the max number of connents reddit loads at once and 100 is what I hope is the mean number or lines they'll take
	for i in range(int(submissionToOpen)+1) :
		submissionWeAreLookingAt = next(submissions)
	commentsPad.addstr(0,0, str(submissionWeAreLookingAt))
	commentsPad.addstr(1,0, "By "+str(submissionWeAreLookingAt.author)+" at "+str(datetime.fromtimestamp(submissionWeAreLookingAt.created)))
	#commentsPad.addstr(0,0,praw.helpers.flatten_tree(submissionWeAreLookingAt.comments)[0].body)	


	commentLevel=0
	leapLines = 3
	wrapper=textwrap.TextWrapper(width=screenMaxX-1, drop_whitespace=False)#replace_whitespace=False)
	#TODO:replace_whitespace eats words, the textrwrap doc suggests use of str.splitlines()


	try :
		for k in wrapper.wrap(submissionWeAreLookingAt.selftext) :
			commentsPad.addstr(leapLines, 0, k)
			leapLines=leapLines+1
	except AttributeError : # no selftext
		#FIXME: doesn't seem to work on link posts
		commentsPad.addstr(leapLines,0,"[no text]")
		leapLines=leapLines+1
	leapLines=leapLines+1

	for i in submissionWeAreLookingAt.comments :
		try :
			commentsPad.addstr(leapLines,0,"---- "+str(i.score)+" : "+str(i.author))
			leapLines=leapLines+1
			for j in wrapper.wrap(i.body) :
				commentsPad.addstr(leapLines, 0, ("  "*commentLevel)+j)
				leapLines=leapLines+1
		except AttributeError :
		#it's a MoreComments
			pass
	commentsPad.addstr(leapLines+2,0,"==EOC==");#TODO: find a better way to prevent user scrolling into the abyss
	commentsPad.refresh(yCoordComments,0,3,1,screenMaxY-1,screenMaxX-1)
	
	while True :
		standardScreen.refresh()
		commentsPad.refresh(yCoordComments,0,3,1,screenMaxY-1,screenMaxX-1)

		userInput = standardScreen.getch()

		if userInput == curses.KEY_DOWN :
			if yCoordComments< (200*100 - screenMaxY-1) :
				yCoordComments = yCoordComments+1
		elif userInput == curses.KEY_UP :
			if yCoordComments>0 :
				yCoordComments = yCoordComments-1
		elif userInput == ord('q') or userInput==ord('Q') :
			break







def main(standardScreen, reddit) :
	curses.curs_set(False)
	curses.use_default_colors()
	screenMaxY, screenMaxX = standardScreen.getmaxyx()

	# no arguments -> interactive mode
	if len(argv) > 1 :
		if argv[1] == 'help' or argv[1] == 'h' or argv[1] == '-h' :
			return 'help'

		else :
			currentSubreddit = argv[1]
			pass 	
		pass
	else :
		currentSubreddit = 'Announcements'
	

	standardScreen.clear()



	submissionsNumberLimit = 25

	yCoord = 0

	# titleWin displays current subreddit
	titleWin = standardScreen.subwin(3, screenMaxX, 0,0)
	titleWin.border()

	titleWin.addstr(1,1, "Sub : "+currentSubreddit)


	submissionsPad = curses.newpad(submissionsNumberLimit*2+1, screenMaxX+1) #submissions number limit times lines per submission

	
	submissionsPad.addstr(0,0,"Fetching submissions..")
	standardScreen.refresh()
	submissionsPad.refresh(yCoord,0,3,1,screenMaxY-1,screenMaxX-1)

	submissions = reddit.get_subreddit(currentSubreddit).get_hot(limit=submissionsNumberLimit)

	while True :


		k=0
		for subIter in submissions :
			#return str(subIter)
			submissionsPad.addstr(k*2, 0, str(k)+'] '+str(subIter))
			submissionsPad.addstr(k*2+1,0,'----------')
			k=k+1



		standardScreen.refresh()
		submissionsPad.refresh(yCoord,0,3,1,screenMaxY-1,screenMaxX-1)

		userInput = standardScreen.getch()

		if userInput == curses.KEY_DOWN :
			if yCoord< (submissionsNumberLimit*2 - screenMaxY +2+3) :
				yCoord = yCoord+1
		elif userInput == curses.KEY_UP :
			if yCoord>0 :
				yCoord = yCoord-1

		elif userInput == ord('m') or userInput == ord('M') :
			# M for 'more', type number of a submission to read it
			submissionToOpen = standardScreen.getstr()
			#TODO : use something a bit more sophisticated than getstr()
			#return str(int(submissionToOpen))
			try :
				if int(submissionToOpen)<submissionsNumberLimit:
					displayComments(standardScreen, screenMaxY, screenMaxX, submissionsPad, reddit, currentSubreddit, submissionToOpen, submissionsNumberLimit)
					submissions = reddit.get_subreddit(currentSubreddit).get_hot(limit=submissionsNumberLimit)
					standardScreen.refresh()
			except ValueError :
				pass
	
		elif userInput == ord('q') or userInput == ord('Q') :
			break


			


appVersion = 'testing v1'

reddit = praw.Reddit(user_agent='PCURB:'+appVersion+' (by /u/m00nnsplit)')
errorType = curses.wrapper(main, reddit)

if errorType == "help" :
	print("ncurses & PRAW -based console reddit browser in Python 3")
	print("pass subreddit name as argument")
	print("please read "+getcwd()+"/readme file for more details")
	exit()
#else :
#	print("error : "+errorType)
#	exit()
